version: '3.9'
services:
  db:
    image: node:18.20-alpine
    container_name: bemobile_db
    command: sh -c "npm install -g json-server && json-server --watch /app/db.json"
    ports:
      - 3000:3000
    volumes:
      - ./db.json:/app/db.json

  frontend:
    container_name: bemobile_frontend
    restart: unless-stopped
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173
    depends_on:
      - db